#
# Copyright (c) 2018 Bosch Software Innovations GmbH and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#

version: '3.7'

volumes:
  vhost:
  challange:

networks:
  proxy_proxy:
    external: true
  sandbox:
    driver: overlay

services:

  # ---------------------
  # hawkBit service
  # ---------------------
  hawkbit:
    image: "hawkbit/hawkbit-update-server:latest"
    networks:
    - proxy_proxy
    - sandbox
    deploy:
      restart_policy:
        condition: on-failure
    environment:
    - 'SPRING_PROFILES_ACTIVE=cloudsandbox'
    - 'SPRING_RABBITMQ_HOST=rabbitmq'
    - 'SPRING_RABBITMQ_USERNAME=guest'
    - 'SPRING_RABBITMQ_PASSWORD=guest'
    - 'VIRTUAL_HOST=hawkbit.eclipseprojects.io'
    - 'LETSENCRYPT_HOST=hawkbit.eclipseprojects.io'

  # ---------------------
  # hawkBit simulator
  # ---------------------
  simulator:
    image: "hawkbit/hawkbit-device-simulator:latest"
    networks:
    - sandbox
    deploy:
      restart_policy:
        condition: on-failure
    environment:
    - 'SPRING_RABBITMQ_VIRTUALHOST=/'
    - 'SPRING_RABBITMQ_HOST=rabbitmq'
    - 'SPRING_RABBITMQ_PORT=5672'
    - 'SPRING_RABBITMQ_USERNAME=guest'
    - 'SPRING_RABBITMQ_PASSWORD=guest'

  # ---------------------
  # RabbitMQ service
  # ---------------------
  rabbitmq:
    image: "rabbitmq:3-management"
    networks:
    - sandbox
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
